services:
  - type: web
    name: espiritualflix-checkout-pix
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: UMBRELLA_API_URL
        value: https://api-gateway.umbrellapag.com/api/user/transactions
      - key: UMBRELLA_API_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
